### ISSUE TITLE
无法部署该项目

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [tiansztiansz/voice-assistant#1]
snowboydetect.py126行,
`return _bootstrap._gcd_import(name[level:], package, level)`
报错：No module named '_snowboydetect'
python版本：3.10.11 
IDE：vscode
系统：windows11 x64
报错截图：
![image](https://user-images.githubusercontent.com/62531937/233730820-44493a75-cf8a-453e-95a7-2704031c622d.png)
其他：
1.本人依赖基本安装完，swig也pip了，但是感觉和这个问题没关系，但是不知道是不是py版本过高导致迟迟未运行成功
2.[snowboydetect.py](https://github.com/tiansztiansz/voice-assistant/blob/main/snowboydecoder.py) 中引用的resources/dong.wav，然而其 并未上传到github，望作者补上

**Comment by tiansztiansz** [comment]
snowboy仅可用于 Linux 系统 和 Mac 系统，你可以使用 windows 的 WSL 安装 Linux 子系统。然后再重新试试能否运行。如有报错可以查看项目 readme.md 中的 参考资料 或向我提问。

后续我还会考虑将项目封装为 Docker 容器，到时候直接拉取下来即可运行。

**Comment by tiansztiansz** [comment]
resources/dong.wav    在  本项目未使用，后续会考虑简化 代码

**Comment by systemoutprintlnhelloworld** [comment]
> snowboy仅可用于 Linux 系统 和 Mac 系统，你可以使用 windows 的 WSL 安装 Linux 子系统。然后再重新试试能否运行。如有报错可以查看项目 readme.md 中的 参考资料 或向我提问。
> 
> 后续我还会考虑将项目封装为 Docker 容器，到时候直接拉取下来即可运行。

不好意思，我没有使用过swig和snowboy，没太听得懂您的话，如果我以下问题问得像个小白，逻辑上不搭调，烦请谅解。
参考资料我看过了的，上面说snowboy在linux上运行的目的貌似是说生成pmdl吧，但是我是想启动`app.py`运行您这个语音助手项目，我看到您录制的[gif](https://github.com/tiansztiansz/voice-assistant/blob/main/src/%E8%AF%AD%E9%9F%B3%E5%8A%A9%E6%89%8B%E6%98%BE%E7%A4%BA%E8%A7%86%E9%A2%91.gif)显示您在vscode for windows下运行了该程序，请问我未能成功运行是因为少运行什么程序呢？

**Comment by systemoutprintlnhelloworld** [comment]
噢噢，我仔细看了下，您的vscode是远程连接到了wsl的，不好意思，这样我大概明白了

**Comment by tiansztiansz** [comment]
嗯是的，你可以在 linux 系统下运行试试

**Comment by systemoutprintlnhelloworld** [comment]
非常感谢，已经部署成功了，貌似由于glibc version>=2.29的限制，在ubuntu 18.04 lts上运行非常麻烦，22.04就好多了
但是
1.那个唤醒词果然还是要自己录一个啊，对着麦克风喊了半天小智都没回应
2.wsl里我已经开启了wslg，但是我单独运行tts.py和运行app.py都没听见ding的声音，而且我把
`play(music_open)
`
放在
`if __name__ == "__main__":`
的最前面，程序居然连等待唤醒都没输出就结束了

**Comment by tiansztiansz** [comment]
1. 唤醒词为 “小智小智”，当你运行 app.py 文件并出现 “等待唤醒” 时，就喊 “小智小智”，唤醒成功时会听到 ding.wav 文件的声音

2. tts.py 是文字转语音模块，并不会调用 ding.wav 文件。该模块用于将聊天机器人的文字转为语音

你可以先跑通示例的 app.py 文件，后面再按需要修改

**Comment by systemoutprintlnhelloworld** [comment]
非常感谢，是wsl没设置默认音频的缘故，目前已经能运行了
在此提几个建议：

1. 开始录音 和 文本转文字 两个过程间 建议加一个提示音 如 dong.wav ，否则用户可能以为机器仍然在识别其语音
2. 建议设置一个 requirement.txt 方便一键下载依赖，.py 文件中未显示表明的依赖 ，如 ffmpeg ,ffprobe等库文件我都是debug出来才发现没装(没有拦截到此报错)
另外 speech2text的模型怎么cpu占用这么高，也有可能是我自己的问题
![image](https://user-images.githubusercontent.com/62531937/233828547-36a9855d-bb3c-4a46-96a2-1b805d5ba1f8.png)

**Comment by tiansztiansz** [comment]
好的，后续有考虑更新代码。

语音转文字的 whisper 模型我放在 cpu 上跑的，因为我的显存在运行 chatyuan 模型时已经跑满了。如果你的显卡性能较好可以放在 gpu 上跑。修改 whisper.py 即可

**Comment by systemoutprintlnhelloworld** [comment]
好的！
